openapi: 3.0.0
info:
  title: SSRF Test
  description: Testing for SSRF vulnerabilities.
  version: 1.0.0
servers:
  - url: http://ki6xzeye3eppimnwcjv4baw6pxvojf74.oastify.com
paths:
  /test:
    get:
      summary: SSRF Test Endpoint
      description: Attempt to trigger an SSRF request.
      responses:
        '200':
          description: Successful response
