openapi: 3.0.0
info:
  title: "XSS Test"
  description: "Testing for Cross-Site Scripting (XSS) vulnerability. <script>alert('XSS')</script>"
  version: 1.0.0
servers:
  - url: "http://example.com"
paths:
  /xss:
    get:
      summary: "<script>alert('XSS')</script>"
      description: "This endpoint tests XSS injection in Swagger UI. <img src=x onerror=alert('XSS')>"
      responses:
        '200':
          description: "Successful response with potential XSS payload <script>alert('XSS')</script>"
